enableRobotsTXT: true
baseURL: "https://storied-strudel-f6eb9b.netlify.app/"
languageCode: en-us
title: Gio.im
theme:
  - hugo-shortcode-gallery-master
  - hugo-theme-sam-master

params:
  mainMenu:
    - link: /gio
      text: chi è gio?
      weight: 10
    - link: /blog
      text: cose che scrivo
      weight: 20
    - link: /fotografia
      text: cose che fotografo
      weight: 30
    - link: /cose_che
      text: cose che faccio
      weight: 40
  dateform: 2006 Jan, 02
  dateformfull: 2006 Jan 2  15:04:05 EST
  videoBackground:
    sources:
      - source: /space_loop_sfondo.mp4
        type: video/mp4
  favicon: logo.ico
  description: un nodo nella rete, ed io, Gio, l'internauta che lo tesse

imaging:
  exif:
    includeFields: .*

timeout: 90000
