enableRobotsTXT = true
baseURL = "https://gioim.netlify.app/"
languageCode = "en-us"
theme = ["hugo-winston-theme", "hugo-shortcode-gallery"]
themesDir = "themes"
title = "Un Nodo nella Rete"
pagination.pagerSize = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = false
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false

  addDot = true
  addFrame = true
  highlightColor = '#F9E400'
  baseColor = "#1F1F1F"
  baseOffsetColor = "#eaeaea"
  headingColor = "#ffffff"
  textColor = "#ffffff"
  dotColor = "#7b16ff"

  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[imaging.exif]
    includeFields = ".*"

[menu]
#  [[menu.main]]
#    identifier = 'home'
#    name = 'Home'
#    url = '/'
#    weight = 1
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 2
    url = "/blog/"
  [[menu.main]]
    name = "Fotografia"
    identifier = "foto"
    weight = 3
    url = "/fotografia/"
  [[menu.main]]
    name = "Libri"
    identifier = "leggo"
    weight = 4
    url = "/libri/"
  [[menu.main]]
    name = "CoseChe"
    identifier = "cose"
    weight = 5
    url = "/cose_che/"
  [[menu.main]]
    name = "AboutMe"
    identifier = "about"
    weight = 6
    url = "/about_me/"
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 6
    url = "/tags/"